services:
  ginwalkers-backend:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - /home/linux/ssl/ginwalkers:/etc/ssl/ginwalkers:ro
      - ./data:/app/data
    networks:
      - swgoh-comlink

networks:
  swgoh-comlink:
  external: true